# CI/CD for Nginx Deployment

name: nginx-ci

on:
  push:
    branches:
      - main
    paths:
      - 'kubernetes/nginx/**'
  pull_request:
    branches:
      - main
    paths:
      - 'kubernetes/nginx/**'

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Push
        uses: docker/build-push-action@v6
        with:
          context: kubernetes/nginx
          file: kubernetes/nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.run_id }}

  updatek8s:
    runs-on: ubuntu-latest

    needs: docker

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in kubernetes deployment manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.run_id }}|" kubernetes/nginx/deploy.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "CI Bot"
          git add kubernetes/nginx/deploy.yaml
          git commit -m "[CI]: Update nginx image tag"
          git push origin HEAD:main
